### PR TITLE
Add adoc report generator

### PR DESCRIPTION
**Pull request by CMon**
An Adoc report generator as alternative/addon to the current pdf generator.

This enables us to have some more theming possibilities or create reports with custom chapters. It also has the ability to automatically create tocs that are able to show up inside modern pdf viewers like requested in #84 
adoc could also be used to create a html version of the report (requested in #49 )

### CODE REVIEW

**Comment by CMon** [comment]
I currently have some open todos:
- [ ] get all basic html code fixed/adjusted that is injected via modules (current open one is <a>)
- [ ] fix all small grey text "footnotes", some i missed during the first run

**Comment by srcnuzn** [comment]
Hey @CMon are there any plans on when to merge your PR? I'm really looking forward to it.

**Comment by CMon** [comment]
Hi @srcnuzn, I have no permission to merge. I used this source to create a Threat Model and handed it to the TÜV for some certification lets hope they are happy with it, otherwise I have to ditch the tool anyway. Until someone with merge permissions merges this feature, you could still go with my forked version: [fix-report-risk-status-error](https://github.com/CMon/threagile/tree/fix-report-risk-status-error) which beside of the number fix that is reported here: #83 also includes the adoc generator.

**Comment by srcnuzn** [comment]
I see. I will try out the forked version if I have some time. If you like, let us know how the certification process went (and which cert you went for). Maybe there is useful feedback for the development of this tool or for other users who evaluate it (like me 🙃).

**Comment by ezavgorodniy** [comment]
Sorry for not coming back for a while, LGTM, just mergeed

**Pull request merged**
