### PR TITLE
change single dash long arguments to double dash long arguments

### PR DESCRIPTION
**Pull request by CMon**
with threagile version > 0.9.0, a single dash for long arguments do not work anymore

### CODE REVIEW

**Comment by ezavgorodniy** [comment]
Could you please add more details on exact example when it's not working for you?

Also @joreiche may share more details on using confi file instead of arguments in command line - that's not documented but may improve a usability of the tool

**Comment by CMon** [comment]
sure:
```
$ docker run --rm -it -v "$(pwd)":/work threagile create-example-model -output /work 
unknown shorthand flag: 'o' in -output
```
and if i use the double dash:
```
$ docker run --rm -it -v "$(pwd)":/work threagile create-example-model --output /work
```
it works even if I also get the help printed as well, same for the -model and --model:
```
$ docker run --rm -it -v "$(pwd)":/work threagile analyze --output /work -model /work/threagile-example-model.yaml
unknown shorthand flag: 'm' in -model
```
and with double dash:
```
$ docker run --rm -it -v "$(pwd)":/work threagile analyze --output /work --model /work/threagile-example-model.yaml
failed to read and analyze model: unable to check risk tracking: Risk tracking references unknown risk (risk id not found) - you might want to use the option -ignore-orphaned-risk-tracking: unencrypted-asset@*
```
even if the example is not working anymore at least it started with the parsing

**Comment by CMon** [comment]
@ezavgorodniy  is there anything else you need as information?

**Comment by ezavgorodniy** [comment]
Conflicts are resolved manually and changes are in master

**Pull request closed without merging**
